import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  await prisma.cluster.deleteMany();
  await prisma.article.deleteMany();
  await prisma.source.deleteMany();

  const sources = [
    {
      id: 'propublica',
      name: 'ProPublica',
      url: 'https://www.propublica.org',
      feedUrl: 'https://www.propublica.org/feeds/propublica/main',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'investigative',
      weight: 1.0,
      isActive: true,
    },
    {
      id: 'npr',
      name: 'NPR',
      url: 'https://www.npr.org',
      feedUrl: 'https://feeds.npr.org/1001/rss.xml',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'news',
      weight: 0.95,
      isActive: true,
    },
    {
      id: 'dw',
      name: 'Deutsche Welle',
      url: 'https://www.dw.com/en/top-stories/s-9097',
      feedUrl: 'https://rss.dw.com/rdf/rss-en-all',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'news',
      weight: 0.9,
      isActive: true,
    },
    {
      id: 'blabbermouth',
      name: 'Blabbermouth.net',
      url: 'https://blabbermouth.net',
      feedUrl: 'https://blabbermouth.net/feed',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'music-metal',
      weight: 0.7,
      isActive: true,
    },
    {
      id: 'musicradar',
      name: 'MusicRadar',
      url: 'https://www.musicradar.com',
      feedUrl: 'https://www.musicradar.com/feeds/all',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'music-gear',
      weight: 0.7,
      isActive: true,
    },
    {
      id: 'sport-cz',
      name: 'Sport.cz',
      url: 'https://www.sport.cz',
      feedUrl: null,
      ingestStrategy: 'rss',
      lang: 'cs',
      tier: 'tier-2',
      editorialIndependence: 'national',
      isWireService: false,
      contentKind: 'sports',
      weight: 0.7,
      isActive: true,
    },
    {
      id: 'wired',
      name: 'Wired',
      url: 'https://www.wired.com',
      feedUrl: 'https://www.wired.com/feed/rss',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'technology',
      weight: 1.0,
      isActive: true,
    },
    {
      id: 'oneusefulthing',
      name: 'One Useful Thing',
      url: 'https://www.oneusefulthing.org',
      feedUrl: 'https://www.oneusefulthing.org/feed',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'ai-newsletter',
      weight: 0.85,
      isActive: true,
    },
    {
      id: 'thehackernews',
      name: 'The Hacker News',
      url: 'https://thehackernews.com',
      feedUrl: 'https://feeds.feedburner.com/TheHackersNews',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'cybersecurity',
      weight: 0.8,
      isActive: true,
    },
    {
      id: 'insideclimatenews',
      name: 'Inside Climate News',
      url: 'https://insideclimatenews.org',
      feedUrl: null,
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'environment',
      weight: 0.85,
      isActive: true,
    },
    {
      id: 'bbc-future-planet',
      name: 'BBC Future Planet',
      url: 'https://www.bbc.com/future-planet',
      feedUrl: null,
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'environment',
      weight: 0.85,
      isActive: true,
    },
    {
      id: 'goodnewsnetwork',
      name: 'Good News Network',
      url: 'https://www.goodnewsnetwork.org',
      feedUrl: 'https://www.goodnewsnetwork.org/feed/',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'positive-news',
      weight: 0.8,
      isActive: true,
    },
    {
      id: 'smiley-movement',
      name: 'Smiley Movement',
      url: 'https://smileymovement.org',
      feedUrl: null,
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'positive-news',
      weight: 0.75,
      isActive: true,
    },
    {
      id: 'qz',
      name: 'Quartz',
      url: 'https://qz.com',
      feedUrl: 'https://qz.com/feed',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'business',
      weight: 0.9,
      isActive: true,
    },
    {
      id: 'yahoo-finance',
      name: 'Yahoo Finance',
      url: 'https://finance.yahoo.com',
      feedUrl: null,
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-1',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'business',
      weight: 0.85,
      isActive: true,
    },
    {
      id: 'fodors',
      name: "Fodor's Travel",
      url: 'https://www.fodors.com',
      feedUrl: 'https://www.fodors.com/feed',
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'travel',
      weight: 0.75,
      isActive: true,
    },
    {
      id: 'lonelyplanet',
      name: 'Lonely Planet',
      url: 'https://www.lonelyplanet.com',
      feedUrl: null,
      ingestStrategy: 'rss',
      lang: 'en',
      tier: 'tier-2',
      editorialIndependence: 'independent',
      isWireService: false,
      contentKind: 'travel',
      weight: 0.8,
      isActive: true,
    },
  ];

  for (const source of sources) {
    await prisma.source.create({ data: source });
  }

  console.log(`Created ${sources.length} sources`);
  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
